const titles={dashboard:'Visão geral',candidaturas:'Candidaturas',profissionais:'Profissionais',pedidos:'Pedidos'};
const getCandidates=()=>JSON.parse(localStorage.getItem('larapeCandidates')||'[]');
const saveCandidates=(v)=>localStorage.setItem('larapeCandidates',JSON.stringify(v));
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function statusClass(s){return s==='Aprovada'?'approved':s==='Entrevista'?'interview':s==='Reprovada'?'rejected':'analysis'}
function render(){const c=getCandidates();const counts={a:c.filter(x=>x.status==='Em análise').length,i:c.filter(x=>x.status==='Entrevista').length,p:c.filter(x=>x.status==='Aprovada').length};
 document.getElementById('totalCandidates').textContent=c.length;document.getElementById('analysisCandidates').textContent=counts.a;document.getElementById('interviewCandidates').textContent=counts.i;document.getElementById('approvedCandidates').textContent=counts.p;document.getElementById('sideCount').textContent=c.length;
 document.getElementById('candidateTable').innerHTML=c.length?c.map(x=>`<tr><td><strong>${esc(x.name)}</strong><br><small>${esc(x.createdAt)}</small></td><td>${esc(x.area)}</td><td>${esc(x.city)}</td><td>${esc(x.phone)}</td><td><span class="status ${statusClass(x.status)}">${esc(x.status)}</span></td><td><span class="cv">${esc(x.cvName)}</span></td><td><select class="action-select" onchange="changeStatus(${x.id},this.value)"><option ${x.status==='Em análise'?'selected':''}>Em análise</option><option ${x.status==='Entrevista'?'selected':''}>Entrevista</option><option ${x.status==='Aprovada'?'selected':''}>Aprovada</option><option ${x.status==='Reprovada'?'selected':''}>Reprovada</option></select></td></tr>`).join(''):'<tr><td colspan="7">Nenhuma candidatura recebida ainda.</td></tr>';
 document.getElementById('recentList').innerHTML=c.slice(0,4).length?`<div class="recent">${c.slice(0,4).map(x=>`<div class="candidate-mini"><div><strong>${esc(x.name)}</strong><small>${esc(x.area)} · ${esc(x.city)}</small></div><span class="status ${statusClass(x.status)}">${esc(x.status)}</span></div>`).join('')}</div>`:'<p>Nenhuma candidatura recebida ainda.</p>';
 const approved=c.filter(x=>x.status==='Aprovada');document.getElementById('approvedList').innerHTML=approved.length?approved.map(x=>`<div class="person"><h3>${esc(x.name)}</h3><p><strong>Área:</strong> ${esc(x.area)}</p><p><strong>Local:</strong> ${esc(x.city)}</p><p><strong>WhatsApp:</strong> ${esc(x.phone)}</p><p><strong>Experiência:</strong> ${esc(x.experience)}</p><p><strong>Disponibilidade:</strong> ${esc(x.availability)}</p></div>`).join(''):'<p>Nenhuma profissional aprovada ainda.</p>';
}
window.changeStatus=function(id,status){const c=getCandidates();const item=c.find(x=>x.id===id);if(item){item.status=status;saveCandidates(c);render();showToast('Status atualizado.');}};
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.side-link').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.side-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');openView(b.dataset.view)}));
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.go)));
function openView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(v).classList.add('active');document.getElementById('pageTitle').textContent=titles[v];render()}
render();
